pub mod builders;
    mod layer; /* private */
pub mod neuron;
mod dyn_snn;
mod snn;

/* Object representing the output spikes generated by a single layer */
#[derive(Debug)]
pub struct SpikeEvent {
    ts: u64,
    spikes: Vec<u8>,
}

impl SpikeEvent {
    pub fn new(ts: u64, spikes: Vec<u8>) -> Self {
        Self { ts, spikes }
    }
}
